POST http://localhost:5000/v1/user
Content-Type: application/json

{
  "userName" : "kaizedsafn9784" ,
  "email" : "kaizen.tdsaf4@gmail.com" ,
  "fullName" : "Vikas Sandhu",
  "password" : "vistagram@123"
}

###
GET http://localhost:5000/v1/user/email/kaizen.tech404@gmail.com/verify

###
POST http://localhost:5000/v1/user/email/verify
Content-Type: application/json

{
  "verificationToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzhiMDY3YS0yNWI0LTQ0YWMtODFiNS1iOWIzYWNlNDA2NzMiLCJpYXQiOjE2MTUwMTk1MTUsImV4cCI6MTYxNTAxOTg3NX0.pF6MWHTEeHJMoWKUNc1JvOUD7dCNzkUQc1gEopBzkGA"
}

###
POST http://localhost:5000/v1/user/login
Content-Type: application/json

{
  "email" : "kaizen.tdsaf4@gmail.com" ,
  "password" : "vistagram@123"
}

###
GET http://localhost:5000/v1/user
