POST http://localhost:5000/v1/user
Content-Type: application/json

{
  "userName" : "kai5555" ,
  "email" : "kaizen2323t.tdsaf4@gmail.com" ,
  "fullName" : "Vikas Sandhu",
  "password" : "vistagram@123"
}

###
GET http://localhost:5000/v1/user/email/kaizen.tech404@gmail.com/verify

###
POST http://localhost:5000/v1/user/email/verify
Content-Type: application/json

{
  "verificationToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTE5YTNmNi1mZDBjLTRhZTItYTIxMy1mZWI1MjY2OWNmYjAiLCJpYXQiOjE2MTUyMDM3MTQsImV4cCI6MTYxNTIwNDA3NH0.vnltIarwcJnVZObo8y723QqzzCLI6lwlHgQtfDcCnFo"
}

###
POST http://localhost:5000/v1/user/login
Content-Type: application/json

{
  "email" : "kaizen2323t.tdsaewf@efmail.com" ,
  "password" : "vistagram23@123"
}

###
GET http://localhost:5000/v1/user
